# dubbo springboot 配置 z01.betadubbo.zk.inf.bandubanxie.com:2181
dubbo:
  application: #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者
    id: cas-live-service
    name: cas-live-service
  registry: #注册中心配置，用于配置连接注册中心相关信息
    address: zookeeper://z01.betadubbo.zk.inf.bandubanxie.com:2181
  protocol: #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受
    name: dubbo
    port: -1
  scan:
    basePackages: com.ysx.cas.api

spring:
  redis:
    database: 0
    host: 172.17.1.81
    port: 6389
    password: yunshuxie1029Password # 密码（默认为空）
    timeout: 6000 # 连接超时时长（毫秒）