# dubbo springboot 配置 crm-live-service bj-localenv-all-01.ecs.inf.bandubanxie.com:2181
dubbo:
  application: #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者
    id: cas-live-service
    name: cas-live-service
  registry: #注册中心配置，用于配置连接注册中心相关信息
    address: zookeeper://bj-localenv-all-01.ecs.inf.bandubanxie.com:2181
  protocol: #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受
    name: dubbo
    port: 20880
  scan:
    basePackages: com.ysx.cas.api

spring:
  redis:
    database: 0
    host: 172.17.1.197
    port: 6399
    password: yunshuxie1029Password # 密码（默认为空）
    timeout: 6000 # 连接超时时长（毫秒）
#    sentinel:
#      master: 172.17.1.197
#      nodes: ["172.17.1.197:6399"]


