# 公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.ysx.cas.dao.bean
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true #启用驼峰映射

# 数据库配置
spring:
  datasource:
    #默认
    main:
      jdbc-url: jdbc:mysql://rm-2ze682yydcln6iai6.mysql.rds.aliyuncs.com:3306/ysx_mooc?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
      username: ysx_prod_writer
      password: RIdqXTBJyQmK8yBqmytnE69OOM1-
      driver-class-name: com.mysql.cj.jdbc.Driver
    #数据组bi库
#    query:
#      jdbc-url: jdbc:mysql://rr-2zely798wfhzmcn84.mysql.rds.aliyuncs.com:3306/ysx_account?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
#      username: ysx_prod_reader
#      password: fUw1QFISW1Nbo20Gd7zGX7aMJJM-
#      driver-class-name: com.mysql.cj.jdbc.Driver
# PageHelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  autoRuntimeDialect: true
