# 公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.ysx.cas.dao.bean
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true #启用驼峰映射

# 数据库配置
spring:
  datasource:
     #默认
     main:
       jdbc-url: jdbc:mysql://172.17.1.239:3317/ysx_mooc?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
       username: ysxmooc
       password: 0127ysxCX@jsb
       driver-class-name: com.mysql.cj.jdbc.Driver
# PageHelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  autoRuntimeDialect: true
