# 公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.ysx.cas.dao.bean
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true #启用驼峰映射

# 数据库配置
spring:
  datasource:
    #默认
    main:
      jdbc-url: jdbc:mysql://rm-2ze682yydcln6iai6.mysql.rds.aliyuncs.com:3306/mooc?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
      username: ysx_prod_writer
      password: RIdqXTBJyQmK8yBqmytnE69OOM1-
      driver-class-name: com.mysql.cj.jdbc.Driver
    #数据组bi库
#    tscp:
#      jdbc-url: jdbc:mysql://rm-2zeiib3ylh08vw5sx.mysql.rds.aliyuncs.com:3306/ysx_data_store?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
#      username: readonly
#      password: sCHGt88yOpzLPkysQ7oqTaCZvJ4-
#      driver-class-name: com.mysql.cj.jdbc.Driver
# PageHelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  autoRuntimeDialect: true
